routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();



Route::group(['middleware' => ['auth', 'admin'], 'prefix' => 'admin'], function() {
    Route::get('/test', function () {
        return view('test');
    });

    Route::resource('skill', 'SkillController');
    Route::resource('vacancy', 'VacancyController');
    Route::resource('users', 'UserController');
    Route::get('/logout', 'Auth\LoginController@logout');
    Route::get('/profile/{id}', 'ProfileController@profileAdmin')->name('admin.profileCreate');
    Route::put('/profile/{id}', 'ProfileController@profileAdminStore')->name('admin.profileStore');
});

Route::group(['middleware' => ['auth', 'user'], 'prefix' => 'user'], function() {
    Route::resource('/profiles', 'ProfileController');
    Route::get('/home', 'VacancyController@userHome')->name('vacancies.home');
    Route::get('/home/{id}', 'VacancyController@userVacancies')->name('vacancies.detail');
    Route::get('/logout', 'Auth\LoginController@logout');
    Route::post('/comment/{id}', 'CommentController@store')->name('user.comment');
});



Route::get('/home', 'HomeController@index')->name('home');

app/Vacancy.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Vacancy extends Model
{
    public $fillable = ['title', 'description', 'salary', 'type', 'duration', 
                        'location', 'skill_req', 'created_at', 'updated_at'];

    public function users(){
        return $this->belongsToMany('App\User');
    }

    public function comments(){
        return $this->hasMany('App\Comment');
    }
}

app/Http/Controllers/VacancyController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Vacancy;

class VacancyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $vacancies = Vacancy::all();
        return view('vacancy.index', compact('vacancies'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('vacancy.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // dd($request->all());
        $vacancy = Vacancy::create([
            'title' => $request->title,
            'type' => $request->type,
            'duration' => $request->duration,
            'salary' => $request->salary,
            'location' => $request->location,
            'skill_req' => $request->skill,
            'description' => $request->description,
        ]);

        return redirect()->route('vacancy.index')->with('status', 'Vacancy Sukses Ditambahkan!!!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $vacancy = Vacancy::find($id);
        return view('vacancy.edit', compact('vacancy'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // dd($request->all());

        $vacancy = Vacancy::find($id)->update([
            'title' => $request->title,
            'type' => $request->type,
            'duration' => $request->duration,
            'salary' => $request->salary,
            'location' => $request->location,
            'skill_req' => $request->skill,
            'description' => $request->description,
        ]);

        return redirect()->route('vacancy.index')->with('success', 'Vacancy Berhasil Diedit');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Vacancy::destroy($id);

        return redirect()->back()->with('success', 'Data Berhasil Dihapus!!');
    }


    public function userHome(){
        $vacancies = Vacancy::all();
        return view('vacancy.userhome', compact('vacancies'));
    }

    public function userVacancies($id){
        $vacancy = Vacancy::find($id);
        return view('vacancy.userDetail', compact('vacancy'));
    }
}

resources/views/vacancy/create.blade.php
@extends('admin-lte.layouts.app')


@section('content')
    <div class="col-md-8 ml-5">
            
        <form 
         action="{{route('vacancy.store')}}" 
         method="post"
         
         class="shadow-sm p-3 bg-white mx-auto">

         {{csrf_field()}}
         
         <div class="form-group">
            <label for="title">Title:</label>
            <input type="text" name="title" id="title" class="form-control">
        </div>

         <div class="form-group">
            <label for="type">Type:</label>
            <select class="form-control" id="type" name="type">
                <option value="part-time" >Part-time</option>
                <option value="full-time" >Full-time</option>
            </select>
          </div>

          <div class="form-group">
            <label for="duration">Duration:</label>
            <select class="form-control" id="duration" name="duration">
                <option value="6bulan" >6 Bulan</option>
                <option value="1tahun" >1 Tahun</option>
            </select>
          </div>

         <div class="form-group">
            <label for="salary">Salary:</label>
            <select class="form-control" id="salary" name="salary">
                <option value="1000000-2000000" >Rp.1000000-Rp.2000000</option>
                <option value="2000000-3000000" >Rp.2000000-Rp.3000000</option>
                <option value="3000000-4000000" >Rp.3000000-Rp.4000000</option>
                <option value="4000000-5000000" >Rp.4000000-Rp.5000000</option>
            </select>
          </div>

          <div class="form-group">
              <label for="location">Location</label>
              <input type="text" name="location" id="location" class="form-control">
          </div>

          <div class="form-group">
            <label for="skill">Skill Requirement: </label>
            <textarea name="skill" id="skill" cols="30" rows="10" class="form-control"></textarea>
         </div>

         <div class="form-group">
            <label for="desctiption">Description: </label>
            <textarea name="description" id="desctiption" cols="30" rows="10" class="form-control"></textarea>
        </div>

       
          <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
@endsection

resources/views/vacancy/edit.blade.php
@extends('admin-lte.layouts.app')


@section('content')
    <div class="col-md-8 ml-5">
            
        <form 
         action="{{route('vacancy.update', [$vacancy->id])}}" 
         method="post"
         
         class="shadow-sm p-3 bg-white mx-auto">

         {{csrf_field()}}
         {{method_field('PUT')}}
         
         <div class="form-group">
            <label for="title">Title:</label>
            <input type="text" name="title" id="title" class="form-control" value="{{$vacancy->title}}">
        </div>

         <div class="form-group">
            <label for="type">Type:</label>
            <select class="form-control" id="type" name="type">
                <option value="part-time" {{$vacancy->type == 'part-time' ? 'selected': ''}}>Part-time</option>
                <option value="full-time" {{$vacancy->type == 'full-time' ? 'selected': ''}}>Full-time</option>
            </select>
          </div>

          <div class="form-group">
            <label for="duration">Duration:</label>
            <select class="form-control" id="duration" name="duration">
                <option value="6bulan" {{$vacancy->duration == '6bulan' ? 'selected': ''}}>6 Bulan</option>
                <option value="1tahun" {{$vacancy->duration == '1tahun' ? 'selected': ''}}>1 Tahun</option>
            </select>
          </div>

         <div class="form-group">
            <label for="salary">Salary:</label>
            <select class="form-control" id="salary" name="salary">
                <option value="1000000-2000000" {{$vacancy->salary == '1000000-2000000' ? 'selected': ''}}>Rp.1000000-Rp.2000000</option>
                <option value="2000000-3000000" {{$vacancy->salary == '2000000-3000000' ? 'selected': ''}}>Rp.2000000-Rp.3000000</option>
                <option value="3000000-4000000" {{$vacancy->salary == '3000000-4000000' ? 'selected': ''}}>Rp.3000000-Rp.4000000</option>
                <option value="4000000-5000000" {{$vacancy->salary == '4000000-5000000' ? 'selected': ''}}>Rp.4000000-Rp.5000000</option>
            </select>
          </div>

          <div class="form-group">
              <label for="location">Location</label>
              <input type="text" name="location" id="location" class="form-control" value="{{$vacancy->location}}">
          </div>

          <div class="form-group">
            <label for="skill">Skill Requirement: </label>
            <textarea name="skill" id="skill" cols="30" rows="10" class="form-control">{{$vacancy->skill_req}}</textarea>
         </div>

         <div class="form-group">
            <label for="desctiption">Description: </label>
            <textarea name="description" id="desctiption" cols="30" rows="10" class="form-control">{{$vacancy->description}}</textarea>
        </div>

       
          <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
@endsection

resources/views/vacancy/index.blade.php
@extends('admin-lte.layouts.app')


@section('content')
<div class="col-md-12">
        @if(Session::get('success'))
          <div class="alert alert-success">
            {{Session::get('success')}}
          </div>
        @endif
      </div>
       
        <div class="container bg-white p-3">
            <div class="row">
                <a href="{{route('vacancy.create')}}" class="btn btn-primary">Create Vacancy</a>
                <table class="table table-striped">
                    <thead>
                      <tr>
                        <th>Title</th>
                        <th>Description</th>
                        <th>Type</th>
                        <th>Duration</th>
                        <th>Action</th>
                      </tr>
                    </thead>
                    <tbody>
                      
                      @foreach ($vacancies as $vacancy)
                      <tr>
                          <td>{{$vacancy->title}}</td>
                          <td>{{$vacancy->description}}</td>
                          <td>{{$vacancy->type}}</td>
                          <td>{{$vacancy->duration}}</td>
                          <td>
                            <a href="{{route('vacancy.edit', ['id' => $vacancy->id])}}" class="btn btn-sm btn-warning">
                              <i class="fa fa-pen" title="edit"></i>
                            </a>
    
                           <form action="{{route('vacancy.destroy', [$vacancy->id])}}" method="post" 
                                 class="d-inline" onsubmit="return confirm('Apakah Anda Yakin Ingin Menghapus?')">
                            {{csrf_field()}}
                            {{method_field('DELETE')}}
    
                            <button type="submit" class="btn btn-danger btn-sm">
                              <i class="fa fa-trash"></i>
                            </button>
    
                           </form>
                          </td>
                      </tr>
                      @endforeach
                      
                    </tbody>
                  </table>
            </div>
        </div>
@endsection

resources/views/vacancy/userDetail.blade.php
@extends('admin-lte.layouts.app')



@section('content')
    {{-- {{dd($vacancy)}} --}}

    <div class="col-md-12">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h1>{{$vacancy->title}}</h1>
                </div>
                <div class="col-md-12">
                    <span class="bg-warning">{{$vacancy->type}}</span>
                    <span class="bg-primary">{{$vacancy->type}}</span>
                    <span class="bg-secondary">{{$vacancy->location}}</span>
                    <span class="bg-dark">{{$vacancy->salary}}</span>
                </div>
                
                
                <p class="col-md-12">{{$vacancy->description}}</p>


                <div class="card">
                    <div class="card-header">
                        Tambahkan Komentar
                    </div>

                    @foreach ($vacancy->comments()->get() as $comment)
                    
                    <div class="card-body">
                        <h1>{{$comment->user->name}}</h1>
                        <p>{{$comment->description}}</p>    
                        <hr>
                    </div>
                    
                    @endforeach
                    
                    <div class="card-body">
                        <form action="{{route('user.comment', [$vacancy->id])}}" method="post">
                            {{csrf_field()}}
        
                            <div class="form-group">
                                <textarea name="comment" id="comment" cols="100" rows="5" class="form-control"></textarea>
                            </div>
        
                            <input type="submit" value="Kirim" class="btn btn-sm btn-primary">
                        
                        </form>
                    </div>
                </div>
               
            </div>
        </div>
    </div>

@endsection

resources/views/vacancy/userhome.blade.php
@extends('admin-lte.layouts.app')


@section('content')
 {{-- {{dd($vacancies)}} --}}
    @foreach ($vacancies as $vacancy)
    
    <div class="container ">
        {{-- <div class="row"> --}}
            <div class="card" >
                <div class="card-header">
                    <h3><a href="{{route('vacancies.detail', [$vacancy->id])}}">{{$vacancy->title}}</a></h3>
                    <span class="bg-warning">{{$vacancy->type}}</span>
                    <span class="bg-primary">{{$vacancy->type}}</span>
                    <span class="bg-secondary">{{$vacancy->location}}</span>
                    <span class="bg-dark">{{$vacancy->salary}}</span>
                </div>
                <div class="card-body">{{str_limit($vacancy->description, 10)}}</div>
                    
            </div>
        {{-- </div> --}}
    </div>
    
    @endforeach
@endsection