routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();



Route::group(['middleware' => ['auth', 'admin'], 'prefix' => 'admin'], function() {
    Route::get('/test', function () {
        return view('test');
    });

    Route::resource('skill', 'SkillController');
    Route::resource('vacancy', 'VacancyController');
    Route::resource('users', 'UserController');
    Route::get('/logout', 'Auth\LoginController@logout');
    Route::get('/profile/{id}', 'ProfileController@profileAdmin')->name('admin.profileCreate');
    Route::put('/profile/{id}', 'ProfileController@profileAdminStore')->name('admin.profileStore');
});

Route::group(['middleware' => ['auth', 'user'], 'prefix' => 'user'], function() {
    Route::resource('/profiles', 'ProfileController');
    Route::get('/home', 'VacancyController@userHome')->name('vacancies.home');
    Route::get('/home/{id}', 'VacancyController@userVacancies')->name('vacancies.detail');
    Route::get('/logout', 'Auth\LoginController@logout');
    Route::post('/comment/{id}', 'CommentController@store')->name('user.comment');
});



Route::get('/home', 'HomeController@index')->name('home');

app/skill.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class skill extends Model
{
    public $table = 'skills';
    public $fillable = ['language_program', 'created_at', 'updated_at'];
}

app/Http/Controllers/SkillController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Skill;

class SkillController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $skills = Skill::all();
        return view('skill.index', compact('skills'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('skill.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        
        $skill = Skill::create([
            'language_program' => $request->language,
        ]);
        return redirect()->route('skill.index')->with('success', 'Skill Berhasil Ditambahkan!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $skill = Skill::find($id);
        return view('skill.edit', compact('skill'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $skill = Skill::find($id);
        $skill->language_program = $request->language;
        $skill->save();

        return redirect()->route('skill.index')->with('success', 'Skill Berhasil Diupdate!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Skill::destroy($id);
        return redirect()->back();
    }
}

resources/views/skill/create.blade.php
@extends('admin-lte.layouts.app')



@section('content')
    <div class="col-md-8 ml-5">
        <form action="{{route('skill.store')}}" method="post" class="shadow-sm p-3 bg-white">
            {{csrf_field()}}

            <div class="form-group">
                <label for="language">Language Program:</label>
                <input type="text" class="form-control" id="text" name="language">
            </div>

            <button type="submit" class="btn btn-primary">Simpan</button>
        </form>
    </div>
@endsection

resources/views/skill/edit.blade.php
@extends('admin-lte.layouts.app')



@section('content')
    <div class="col-md-8 ml-5">
        <form action="{{route('skill.update', [$skill->id])}}" method="post" class="shadow-sm p-3 bg-white">
            {{csrf_field()}}
            {{method_field('PUT')}}
            <div class="form-group">
                <label for="language">Language Program:</label>
                <input type="text" class="form-control" id="text" name="language" value="{{$skill->language_program}}">
            </div>

            <button type="submit" class="btn btn-primary">Simpan</button>
        </form>
    </div>
@endsection

resources/views/skill/index.blade.php
@extends('admin-lte.layouts.app')



@section('content')
  <div class="col-md-8">
    @if(Session::get('success'))
      <div class="alert alert-success">
        {{Session::get('success')}}
      </div>
    @endif
  </div>
   
    <div class="container bg-white p-3">
        <div class="row">
            <a href="{{route('skill.create')}}" class="btn btn-primary">Create Skill</a>
            <table class="table table-striped">
                <thead>
                  <tr>
                    <th>Name</th>
                    <th>Action</th>
                  </tr>
                </thead>
                <tbody>
                  
                  @foreach ($skills as $skill)
                  <tr>
                      <td>{{$skill->language_program}}</td>
                      <td>
                        <a href="{{route('skill.edit', ['id' => $skill->id])}}" class="btn btn-sm btn-warning">
                          <i class="fa fa-pen" title="edit"></i>
                        </a>

                       <form action="{{route('skill.destroy', [$skill->id])}}" method="post" 
                             class="d-inline" onsubmit="return confirm('Apakah Anda Yakin Ingin Menghapus?')">
                        {{csrf_field()}}
                        {{method_field('DELETE')}}

                        <button type="submit" class="btn btn-danger btn-sm">
                          <i class="fa fa-trash"></i>
                        </button>

                       </form>
                      </td>
                  </tr>
                  @endforeach
                  
                </tbody>
              </table>
        </div>
    </div>
@endsection