routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();



Route::group(['middleware' => ['auth', 'admin'], 'prefix' => 'admin'], function() {
    Route::get('/test', function () {
        return view('test');
    });

    Route::resource('skill', 'SkillController');
    Route::resource('vacancy', 'VacancyController');
    Route::resource('users', 'UserController');
    Route::get('/logout', 'Auth\LoginController@logout');
    Route::get('/profile/{id}', 'ProfileController@profileAdmin')->name('admin.profileCreate');
    Route::put('/profile/{id}', 'ProfileController@profileAdminStore')->name('admin.profileStore');
});

Route::group(['middleware' => ['auth', 'user'], 'prefix' => 'user'], function() {
    Route::resource('/profiles', 'ProfileController');
    Route::get('/home', 'VacancyController@userHome')->name('vacancies.home');
    Route::get('/home/{id}', 'VacancyController@userVacancies')->name('vacancies.detail');
    Route::get('/logout', 'Auth\LoginController@logout');
    Route::post('/comment/{id}', 'CommentController@store')->name('user.comment');
});



Route::get('/home', 'HomeController@index')->name('home');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function profile(){
        return $this->hasOne('App\Profile', 'user_id');
    }

    public function vacancies(){
        return $this->belongsToMany('App\Vacancy');
    }

    public function comments(){
        return $this->hasMany('App\Comment');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::with('profile')->where('role', '=', '0')->get();
        return view('user.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        User::destroy($id);

        return redirect()->back()->with('success', 'User Berhasil Dihapus');
    }
}

resources/views/user/index.blade.php
@extends('admin-lte.layouts.app')


@section('content')
{{-- @foreach ($user as $user)
    {{dd($user->profile->photo)}}
@endforeach --}}
 <div class="col-md-12">
   @if(Session::get('success'))
    <div class="alert alert-success">
      {{Session::get('success')}}
    </div>
    @endif
 </div>
<div class="container">           
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Name</th>
              <th>Email</th>
              <th>Photo</th>
              <th>Action</th>
            </tr>
          </thead>
          @foreach ($users as $user)
          <tbody>
              <tr>
                <td>{{$user->name}}</td>
                <td>{{$user->email}}</td>
                <td><img src="{{ asset("storage/".$user->profile->photo) }}" alt="" class="elevation-2" witd="70px" height="150"></td>
                <td>
                  <form action="{{route('users.destroy', [$user->id])}}" method="post">
                    {{method_field('DELETE')}}
                    {{csrf_field()}}

                    <button type="submit" class="btn btn-sm btn-danger" onclick="return confirm('Apakah Anda Yakin?')">
                      <i class="fa fa-trash"></i>
                    </button>
                  </form>
                </td>
              </tr>
              
            </tbody>
          @endforeach
          
        </table>
      </div>
@endsection